### ISSUE TITLE
Gource hangs in Git bash, requires pressing Enter

### ISSUE THREAD

**Issue by ferenczy** [acaudwell/Gource#101]
When I execute `gource` in Git bash, it prints or does nothing and it looks like it's hang, although it just requires to press <kbd>Enter</kbd>:

    $ gource --help

Until I press <kbd>Enter</kbd>, the command doesn't do anything.

Although it depends on how Git bash is executed. If it's executed using `git-bash.exe` (`C:\Program Files\Git\git-bash.exe`), which is the default, used by for example SourceTree, it behaves as I described above. When executed using `bash.exe` (`"C:\Program Files\Git\usr\bin\bash.exe" --login -i`) it prints the help immediately as in plain Windows Console or Cygwin.

Operating system: Windows 7 64-bit
Gource version: 0.42
Git version: 2.12.0 64-bit

**Comment by acaudwell** [comment]
The existing mechanism to detect if gource is opened in an existing console window (it attempts to query the position of the console with GetConsoleScreenBufferInfo()) seems to not work in the case you describe.

I think a simple work around might be that I check if the TERM env variable exists.
