### ISSUE TITLE
Captions does not display

### ISSUE THREAD

**Issue by dotnetCarpenter** [acaudwell/Gource#102]
I can not get the caption feature to work. I've used `git log --no-walk --tags --pretty="%at|%an released version %D"` to produce the caption file [gource.caption.txt](https://github.com/acaudwell/Gource/files/916708/gource.caption.txt).

And I run *gource* with: `gource -r 25 --file-filter node_modules -c 4.0 --multi-sampling --logo logo-svg-js-01d-128.png --caption-file gource.caption.txt --caption-size 24 --camera-mode track --caption-colour FF0066 --caption-duration 6 ../svg.js/`

The project (../svg.js) is this one: https://github.com/svgdotjs/svg.js

@acaudwell Thanks for an awesome project!

Not sure what info you need about my system so here is what I have readily available:

Gource configured with `./configure --with-tinyxml`
Gource version: 0.45 (latest commit from master f5d8f1b)
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
libboost-filesystem-dev/xenial,now 1.58.0.1ubuntu1 amd64 [installed]
libfreetype6-dev/xenial,now 2.7.1-0ubuntu0.16.04.2ppa2 amd64 [installed]
libglew-dev/xenial,now 1.13.0-2 amd64 [installed]
libglm-dev/xenial,xenial,now 0.9.7.2-1 all [installed]
libpcre3-dev/xenial,now 2:8.39-1+deb.sury.org~xenial+1 amd64 [installed]
libpng12-dev/xenial,now 1.2.54-1ubuntu1 amd64 [installed]
libsdl2-dev/xenial,now 2.0.4+dfsg1-2ubuntu2 amd64 [installed]
libsdl2-image-dev/xenial,now 2.0.1+dfsg-2 amd64 [installed]
libtinyxml-dev/xenial,now 2.6.2-3 amd64 [installed]

**Comment by dotnetCarpenter** [comment]
Can it be line endings in [gource.caption.txt](https://github.com/acaudwell/Gource/files/916708/gource.caption.txt)?

**Comment by acaudwell** [comment]
It doesn't look like the file is in chronological order.

**Comment by dotnetCarpenter** [comment]
You mean that they should be in ascending order? Right now they are in descending order as that is what `git log --no-walk --tags --pretty="%at|%an released version %D` gives.

**Comment by dotnetCarpenter** [comment]
Just reread the [wiki](https://github.com/acaudwell/Gource/wiki/Captions#example). Thanks for pointing that out.

**Comment by dotnetCarpenter** [comment]
Unfortunately that doesn't help. If you have time, you can clone my repo, `git clone --depth=1 https://github.com/dotnetCarpenter/svg.js_visualization_videos.git && cd svg.js_visualization_videos && git submodule update` and reproduce the issue.

The commands I use are in the [README](https://github.com/dotnetCarpenter/svg.js_visualization_videos#commands-for-gource).

**Comment by acaudwell** [comment]
Looks like its in descending order now...

**Comment by dotnetCarpenter** [comment]
@acaudwell You are right. Sorry about that. In the last commit everything was mistakenly deleted.
[That is now fixed](https://github.com/dotnetCarpenter/svg.js_visualization_videos/blob/master/gource.caption.txt). But still no change. In fact it doesn't even work with the old command that I saved in the README. Gource ignores the last path and display the svg.js_visualization_videos repository history instead... Hmmm...

**Comment by dotnetCarpenter** [comment]
@acaudwell Just tried from clone of svg.js that is not a submodule and it works.`gource -r 25  -c 4.0 --caption-file /home/dotnet/projects/playground/svg.js_visualizations/gource.caption.txt`

Guess Gource doesn't pick up the `.git` folder in submodules for some reason. But that is however another issue.

The main point: *Captions has to be in **ascending order**!*

**Comment by tom-lord** [comment]
Ancient thread, but jumping in here in case someone else runs into it...

Another caveat to captions is that they must be an **exact match** against a timestamp in the gource log.

For example, you cannot just add an annotation like `2019-06-03|Product goes live!`; the timestamp has to match _exactly_ with something in the log.
