### ISSUE TITLE
Feature request: filter by filetype

### ISSUE THREAD

**Issue by tehyosh** [acaudwell/Gource#106]
I work on a game and in the git repo we have both code and assets like images, 3d models, sounds, etc, I'd like to do separate videos of the code files and of the asset files but there's no way to display only certain extensions or exclude some extensions.

**Comment by acaudwell** [comment]
The next version has a --file-show-filter option.

Right now you can use --output-custom-log FILE to output a pipe delimited file you can relatively easily filter by file type.
