### ISSUE TITLE
Error: SDL_image with PNG support (Ubuntu 16.04)

### ISSUE THREAD

**Issue by ricomoss** [acaudwell/Gource#109]
I recently updated to Ubuntu 16.04 and I can no longer successfully run the configure script.

```
checking for IMG_LoadPNG_RW... no
configure: error: SDL_image with PNG support required. Please see INSTALL
```

I have been unable to get any further info from `INSTALL`.  I've manually built SDL_image to support PNG and continue to see this error.

Please advise.

**Comment by acaudwell** [comment]
If you install libsdl2-dev and  libsdl2-image-dev as per the INSTALL file does it work?

Also FYI I am removing the deprecated SDL 1.2 support, in case it is something to do with that.

**Comment by ricomoss** [comment]
Thank you for the quick response.  I've followed the INSTALL instructions exactly with no luck.  I've since tried multiple versions of `SDL_image`, including building/compiling locally with and without several options.  No luck.

I initially tried with SDL 2, then with 1.2 (just to see if I could get it working) and I have since switched back to 2.  I've tried many iterations and haven't been able to get past the error message.

**Comment by ricomoss** [comment]
As is most things when coding...as soon as I reach out to someone about the problem it gets resolved.

I decided to `apt-get remove` all things SDL and start again from scratch.  It worked.  I'm not sure what I did "correctly" this time, but for anyone who comes to this in the future: Try to remove SDL and reinstall it.
