### ISSUE TITLE
SDL initialization failed - Failed to connect to the Mir Server

### ISSUE THREAD

**Issue by elJoeyJojo** [acaudwell/Gource#111]
Hello,

Very very new to Gource, Kibana, Elasticsearch but started setting up Diskover so I can set it up with Gource. Kibana and Elasticsearch are setup and configured correctly but I can't even initialize Gource and I don't know why. I'm using Ubuntu 16.04

I set it up by GIT cloning Gource v0.45, I installed all the libraries and packages needed. Ran the autogen.sh file, ./configured && make with no issues. Ran make install with no issues but when I try to run $ gource I get "SDL initialization failed - Failed to connect to Mir Server" 

I don't know what that is so I looked it up and saids I need Unity so Installed unity8-desktop-session-mir rebooted the server and still get the same issue. Can anybody help me out?

I just wanna set this up and start playing around with Gource.

Thank you very much!

**Comment by acaudwell** [comment]
You wouldn't normally run Gource on a server as it won't usually have a GPU. I assume the Diskover Gource script is intended to run on your desktop and you pipe data from the server into it.
