### ISSUE TITLE
Gource adds src or vendor folders for GO projects, resulting in overblown bloom trees

### ISSUE THREAD

**Issue by Cryson** [acaudwell/Gource#113]
I think it'd be a good idea to have a flag for go repositories, and/or have it in the code to ignore vendor and src folders in GO github project folders.

Reason for this is when I run gource against a repository containing go code, it blooms out the vendor/src folders resulting in a complete mess.

Opinions on this matter?

**Comment by davidjeddy** [comment]
Does the repo for your project also ignore the vendor/src dir? Gource reads the Git Log history to know what to render. As such if the dir is part of your repo, gource renders it.

**Comment by Cryson** [comment]
@davidjeddy No it does not, best practices for Golang projects is to add the entire vendor folder as part of your git repository to lock in go dependency versions for others to consume.

Therefore when running gource against a go project since the vendor folder is part of the project it get's rendered and explodes the tree. Not sure if we could ignore vendor when reading the git log for golang based projects or not?

**Comment by acaudwell** [comment]
The --file-filter option also can be used to exclude directories (it actually looks at the full file path). Probably the best way to deal with it rather than try to detect what language the project is.

**Comment by davidjeddy** [comment]
What would the effort amount be for creating an alias `--directory-filter` for `--file-filter` that focuses on directory, not file, filtering REGEX patterns?

**Comment by acaudwell** [comment]
I should probably update the documentation to clarify that it looks at the whole path not just the filename.

**Comment by Cryson** [comment]
Just to confirm, doing `--file-filter src` and `--file-filter vendor` resolved the issue for go repositories. Thanks for the information guys!

 As a user when reading the documentation file filter read as a regex going against a file and not a path. Updated README for `--file-filter` or an alias as stated above would definitely stop confusion.
