### ISSUE TITLE
Update TinyXML?

### ISSUE THREAD

**Issue by K2** [acaudwell/Gource#114]
There's been some important fixes for improving the version of tinyXML you're on;

leethomason/tinyxml2#486

Thanks

**Comment by acaudwell** [comment]
That bug is in TinyXML2 rather than the original TinyXML, of which Gource is using the most recent version. Not sure if there are serious issues with the one we're using. Apparently TinyXML2 has a different API.

**Comment by K2** [comment]
Yeah, I wasn't looking close enough at the versioning, thx :D
