### ISSUE TITLE
[question] How to use Gource without installing Git?

### ISSUE THREAD

**Issue by Dan9er** [acaudwell/Gource#115]

**Comment by daemonstorm** [comment]
My suggestion, use the custom log format.

https://github.com/acaudwell/Gource/wiki/Custom-Log-Format

So, you'd have to have access to git or cvs somewhere to create the log from and then use that log file to run gource with.

**Comment by Dan9er** [comment]
Are there tools that convert a Git log to a Gource log?

**Comment by acaudwell** [comment]
Gource can do that with --output-custom-log FILE, though you need Git on the computer you generate the custom log on.
