### ISSUE TITLE
readme needs an md extension and possibly some editing to follow markdown

### ISSUE THREAD

**Issue by revelt** [acaudwell/Gource#123]
hi guys!

What an awesome piece of software. Let's put it up to the baseline of all other libs here on GitHub and a) set readme's extension to MD, and b) format the readme properly in markdown.

This will open huge opportunities for badges as well.

cheers!

**Comment by Dan9er** [comment]
See PR #29.

**Comment by revelt** [comment]
Thank you. When it's merged let's close. There is no issue regarding this atm, I looked.

**Comment by revelt** [comment]
looks like PR went stale.. closing.
