### ISSUE TITLE
How to use it? It always say me "directory not supported"

### ISSUE THREAD

**Issue by Julio974** [acaudwell/Gource#125]
I'm not good at programming, and I'd like to try to use Gource. I downloaded the zip file, but when I type:
`gource`
it answers me:
``gource: directory not supported
Try 'Gource --help' for more information``
I'd like to know how to correct this problem!
Thank you in advance!

**Comment by acaudwell** [comment]
You need `git` and you need to either run gource inside a git repository directory or specify the directory as the argument to gource i.e. `gource path/to/your/git/repo`.

**Comment by Julio974** [comment]
Can I have more details please? I'm a beginner and I don't know how to "run gource inside a git repository directory or specify the directory as the argument to gource i.e. gource path/to/your/git/repo."
