### ISSUE TITLE
Fails to build on Alpine (x86_64 and ppc64le)

### ISSUE THREAD

**Issue by rgdoliveira** [acaudwell/Gource#131]
I'm trying to build gource 0.47 on Alpine Linux Edge (next 3.7 version) and it is failing to build with error:

In file included from /usr/include/directfb/directfb++.h:35:0,
                 from /usr/include/directfb/directfb.h:32,
                 from /usr/include/SDL2/SDL_syswm.h:83,
                 from src/core/sdlapp.cpp:31:
/usr/include/directfb/direct/Types++.h:46:6: error: template with C linkage
      template <typename _Item> class List;
      ^~~~~~~~
/usr/include/directfb/direct/Types++.h:47:6: error: template with C linkage
      template <typename _Item> class ListLocked;
      ^~~~~~~~
/usr/include/directfb/direct/Types++.h:48:6: error: template with C linkage
      template <typename _Item> class ListSimple;
      ^~~~~~~~
/usr/include/directfb/direct/Types++.h:50:6: error: template with C linkage
      template <typename _CharT> class StringBase;
      ^~~~~~~~
/usr/include/directfb/direct/Types++.h:51:6: error: template with C linkage
      template <typename _CharT> class StringsBase;
      ^~~~~~~~

I'm building it with:
$ ./configure --prefix=/usr
$  make

And Alpine has directfb version 1.7.7.

The full build log is available at: http://build.alpinelinux.org/buildlogs/build-3-7-x86_64/community/gource/gource-0.47-r1.log

**Comment by acaudwell** [comment]
Looks like this was patched in SDL2 for Apline Linux shortly after the issue was created:
https://github.com/alpinelinux/aports/commit/bf9e945981a04cac944060f2d644d9d8ca216ae1
