### ISSUE TITLE
Caption file location/path syntax

### ISSUE THREAD

**Issue by geekkid1** [acaudwell/Gource#138]
Can you go a little more in depth on the captions? I created a simple set of 2 captions, pipe delim, in the right order, but they don’t show up. I can’t get the file to you right now as I can not access the machine I put it on right now, but I will ASAP. But also, just in general, maybe go a bit more in depth for those of us (like me) somewhat new to this kind of thing. 

Oh. One more thing. Where do I put my caption file? If it doesn’t matter, how do I specify the file path?

**Comment by acaudwell** [comment]
You specify the path to the file including the filename as the --caption-file argument. I checked and it doesn't actually give you a message if the path is wrong or the file doesn't exist so this might be why it's not working.

**Comment by geekkid1** [comment]
So like —caption-file c:/path/to/file.txt
Or —caption-file “c:/path/to/file.txt”
*or* —caption-file ../relative/path/to/file.txt

Which one of those would be correct?

**Comment by acaudwell** [comment]
I think those would all work. If there is a space in the path you'd want the double quotes around the path.

**Comment by geekkid1** [comment]
Ok, thanks

**Comment by geekkid1** [comment]
I figured out that I misspelled the filename in the command. It works now. It's always something staring me right in the face.
