### ISSUE TITLE
help displays wrong string delimiters

### ISSUE THREAD

**Issue by Bananeweizen** [acaudwell/Gource#139]
The help screen shows multiple options that can take string values, e.g. start-date. Those are delimited by some single quote character. However, when running gource on Windows, those strings must be delimited by double quote characters. Copy-pasting from the help screen to the command line leads to gource not recognizing the option value.

**Comment by davidjeddy** [comment]
Out of curiosity are you able to use a string escape character w/ the single quotes?

**Comment by Bananeweizen** [comment]
When using the windows command line escape character ^ then it doesn't show an error anymore, but the result is wrong nevertheless, since it leads to using the quote character literally in the date format string. So in the end only double quotes work correctly on Windows.

That also fits the experience of others with cross OS command lines, like shown here: https://superuser.com/questions/324278/how-to-make-windows-command-prompt-treat-single-quote-as-though-it-is-a-double-q

**Comment by davidjeddy** [comment]
Ah, fair enough. Guess Gource's argument parsing needs a looking at.

**Comment by acaudwell** [comment]
Changed to double quotes. Thanks.
