### ISSUE TITLE
Add support for user nicknames

### ISSUE THREAD

**Issue by GramThanos** [acaudwell/Gource#141]
It would be great to be able to re-name users.
By doing that we would be able to re-name users that appear as 2 users but are one.

**Comment by mschilli87** [comment]
@GramThanos: You could a) re-write the git history using `git filter-branch` or b) extract, modify & specify the log for `gource`, e.g.:

```sh
OLD="<user-to-replace>" &&
NEW="<user-to-replace-with>" &&
TMP="$(mktemp)" &&
gource --output-custom-log /dev/stdout \
| gawk \
   -F\| -vOFS=\| \
   -vold="$OLD" -vnew="$NEW" \
   '$2==old{$2=new}1' \
> "$TMP" &&
gource $TMP &&
rm $TMP
```

**Comment by GramThanos** [comment]
Seems a good solution.
