### ISSUE TITLE
Windows not working

### ISSUE THREAD

**Issue by STEAKISAWAKE** [acaudwell/Gource#142]
I have tried every thing to get the latest version of Windows working but nothing is working. It keeps telling me that "gource : directory not found". I don't know what it means but I need help.

**Comment by acaudwell** [comment]
I don't think there is a 'directory not found' error message. If it is 'directory not supported' this means it cannot work out what version control system the repository is. Make sure the directory path is correct. You might need to wrap it in double quotes if it has spaces in it.

**Comment by mschilli87** [comment]
@STEAKISAWAKE: Also see https://github.com/acaudwell/Gource/issues/130 for a similar issue with some additional debugging advice.

**Comment by STEAKISAWAKE** [comment]
@acaudwell what do you mean by version control system? And also I did have a typo, It was Directory not supported.

**Comment by mschilli87** [comment]
@STEAKISAWAKE: You opened an issue for a software that describes itself as 'software version control visualization' but you don't know what a [version control system](http://lmgtfy.com/?iie=1&q=version+control+system) is? What exactly do you try use gource for?

**Comment by STEAKISAWAKE** [comment]
I am trying to use gource for what it was created to do,  Visualize progress happening.

**Comment by STEAKISAWAKE** [comment]
I'm pretty sure I know what version control system is, I just call it something different.

**Comment by acaudwell** [comment]
Check out the discussion on #130 as @mschilli87 helpfully pointed out as it seems like the same issue.

**Comment by STEAKISAWAKE** [comment]
The thing is I've tested it out on multiple Windows computers. I get the same problem every time

**Comment by STEAKISAWAKE** [comment]
Thank you for your help
