### ISSUE TITLE
Unknown options :skull:

### ISSUE THREAD

**Issue by DataDrug** [acaudwell/Gource#144]
Hi, I just found out about gource.

Can i see a sintax example ? 

I was trying to use: (based on what I found somewhere online)

gource -1280x720 -o gource.ppm C:\Path\to\git\folder-master C:\Path\To\ffmpeg-20180124-1948b76-win64-static\bin\ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i gource.ppm -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.x264.avi

And I get this: 

gource: unknown option y
Try 'gource --help' for more information.

Sorry if the question is basic.

**Comment by mschilli87** [comment]
To me it looks like you are running two commands together:

```sh
gource -1280x720 -o gource.ppm C:\Path\to\git\folder-master
```

is the Gource command creating a video file `gource.ppm` and

```sh
C:\Path\To\ffmpeg-20180124-1948b76-win64-static\bin\ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i gource.ppm -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.x264.avi
```

is the ffmpeg command to convert the video in `gource.ppm` to `gource.x264.avi`.

If you run them one at a time, it should work.

The way you put it, the second command is interpreted as additional parameters to the first, so the `-y` switch for `ffmpeg` is passed to `gource` which doesn't understand it and fails with the correct error message.

**Comment by DataDrug** [comment]
Magic is happening!
