### ISSUE TITLE
Gource behaves incorrectly with glm 0.9.9.0

### ISSUE THREAD

**Issue by AMDmi3** [acaudwell/Gource#156]
I was testing `glm` update from 0.9.8.5 to 0.9.9.0 in FreeBSD, and it turned out that it breaks gource behavior - while with 0.9.8.5 it works well, with 0.9.9.0 the output becomes antsy and convulsive at some point - when new directories appear in repository, they start to jump left and right instead of smoothly distributing into usual flower-like structure. I can try to record a video if you cannot reproduce this.

Also, glm has hidden some experimental features by default, so gource now needs ` -DGLM_ENABLE_EXPERIMENTAL=1` in compiler flags.

**Comment by AMDmi3** [comment]
Please ignore the note about GLM_ENABLE_EXPERIMENTAL, I've just discovered that FreeBSD had non-latest gource 0.47. But the bug is present in 0.48 too.

Here are videos produced with gource 0.48 with glm 0.9.8.5 and 0.9.9.0:

https://people.freebsd.org/~amdmi3/gource-glm-0.9.8.5.mp4
https://people.freebsd.org/~amdmi3/gource-glm-0.9.9.0.mp4

**Comment by acaudwell** [comment]
Hi,
Didn't know GLM 0.9.9.0 had come out. Thanks.

Add `-DGLM_FORCE_CTOR_INIT` to fix the undefined behaviour. It does this on master but hasn't been in a release yet.

The decision to change constructors to not initialize values and make GLM backwards incompatible has been very frustrating to deal with.

Background:
https://github.com/g-truc/glm/issues/735

**Comment by AMDmi3** [comment]
It works, thanks! Is there info on potential breakages in other `glm` consumers?

**Comment by acaudwell** [comment]
I'd be tempted to just patch GLM to always define `GLM_FORCE_CTOR_INIT` and `GLM_ENABLE_EXPERIMENTAL` since they make it backwards compatible again and save everyone a headache.
