### ISSUE TITLE
Add option to limit dirname display by directory depth

### ISSUE THREAD

**Issue by svdHero** [acaudwell/Gource#157]
Displaying all directory names in big trees clutters the screen. Using the option "--hide dirnames" removes all directory names. Neither of these extremes is what I usually want.

Instead, it would be great to have an option like "--max-dirname-depth" where one could specify the directory depth until where the directory names are shown. That way the top level directories could still be identified whereas the smaller, more dense parts of the tree are not covered by countless unreadable sub-directory names.

**Comment by ctaepper** [comment]
i second that

**Comment by badsyntax** [comment]
Fort those stumbling across this issue, it looks like this feature has been available since 2014, via the `--dir-name-depth DEPTH` option ([commit here](https://github.com/acaudwell/Gource/commit/6f631d9860d03cc4dff3724acab317a81d3c73f9)).

**Comment by Xaxetrov** [comment]
Proposal to close this issue
