### ISSUE TITLE
Request - Show commit messages

### ISSUE THREAD

**Issue by Ruffo324** [acaudwell/Gource#160]
I think it would be great if the commit messages could be displayed as well. Could that be done?

**Comment by michaelpalumbo** [comment]
Hi @Ruffo324 

You can set it using the caption file command:
https://github.com/acaudwell/Gource/wiki/Captions

**Comment by kres0345** [comment]
I've arrived at this solution: `git log --pretty=format:"%at|%s" --reverse --no-merges > commitmsg.txt`,
- `%at` is the author-date in unix time.
- `%s` is the subject of the commit.
- `--reverse` to output dates in chronological order.
- `--no-merges`  to not include generic merge commit messages.
- `>` to pipe into a file `commitmsg.txt`

Run the command in the same directory as you would run `gource`.
Finally to display captions: `gource --caption-file commitmsg.txt`.

Sources:
https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History
http://schacon.github.io/git/git-show

**Comment by michaelpalumbo** [comment]
> I've arrived at this solution: `git log --pretty=format:"%at|%s" --reverse --no-merges > commitmsg.txt`,
> 
> * `%at` is the author-date in unix time.
> * `%s` is the subject of the commit.
> * `--reverse` to output dates in chronological order.
> * `--no-merges`  to not include generic merge commit messages.
> * `>` to pipe into a file `commitmsg.txt`
> 
> Run the command in the same directory as you would run `gource`.
> Finally to display captions: `gource --caption-file commitmsg.txt`.
> 
> Sources:
> https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History
> http://schacon.github.io/git/git-show

nice!

**Comment by Dragonisser** [comment]
Doesnt seem like gource had any updates since a while, so why doesnt this work anymore?

**Comment by kres0345** [comment]
What do you mean, can't it display a caption file anymore?

**Comment by Dragonisser** [comment]
> What do you mean, can't it display a caption file anymore?

It didnt show any captions if i didnt run it via git bash. Powershell, cmd, etc. just simply ignored the caption file for some reason.

**Comment by acaudwell** [comment]
I think it might not work from powershell because the caption file produced by running that command ends up being UTF16 (I checked using the `file` command from inside `git bash`):
`commitmsg.txt: Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators`

I found a way to run the command on powershell to get a compatible file by avoiding using the `>` operator and use the `--output` git log option:
` git log --pretty=format:"%at|%s" --reverse --no-merges --output commitmsg.txt`

**Comment by mathieu-aubin** [comment]
i love this discussion btw. Had a thought about having gource use xml log input ( as the standard MUST support for handling utf8 by nature, on every platform and processors) and if interrested in following such idea... https://groups.google.com/g/git-users/c/2bxVkNAB2EE seems to somewhat reflect the same problem, ages ago tho
