### ISSUE TITLE
Video recommendations on Wiki produce huge files

### ISSUE THREAD

**Issue by andrewducker** [acaudwell/Gource#161]
https://github.com/acaudwell/Gource/wiki/Videos suggests a CRF of 1 and a preset of "ultrafast" for calling FFmpeg.

These parameters will produce files that are massively larger than they need to be - around 4 times the size for me.

https://trac.ffmpeg.org/wiki/Encode/H.264#FAQ suggests that a CRF of 17 is effectively lossless (and certainly looks so to me).  Processing with this, and a preset of "medium" gives me a file which is approximately a quarter the size of the one produced with the example command line.

Also, because a PPM file is massive, it's likely that the conversion will be constrained by disk speed in any case - the slowness of reading through the 43GB ppm file from my SSD meant that the FFmpeg CPU usage couldn't get above 50% (across all cores).  So there's not much point going for "ultrafast".

Could the wiki be updated?

**Comment by andrewducker** [comment]
For example:
-y -r 60 -f image2pipe -vcodec ppm -i gource.ppm -vcodec libx264 -preset medium -pix_fmt yuv420p -crf 17 -threads 0 -bf 0 gource.avi

**Comment by acaudwell** [comment]
Thanks. I've added some notes about your points regarding the CRF and preset and changed the preset in the example to medium. I did notice quite a big difference in the bloom quality with the higher CRF so I left the old value in the example.
