### ISSUE TITLE
the purpose of --transparent option is 'unclear'

### ISSUE THREAD

**Issue by skybldev** [acaudwell/Gource#164]
I have tried using the `--transparent` option on Windows 10, and the background doesn't become transparent. Just to get on the same page in case I'm missing what it's supposed to do, I expect the background to be transparent and show the area under it, like if I was running the viewport over a browser window, it would show the contents of the browser window.

**Comment by davidjeddy** [comment]
@Luxray5474 could you provide the entire CLI command you are running please.

**Comment by Luxray5474** [comment]
@davidjeddy `gource --transparent`

https://i.imgur.com/Gr6AdUD.gifv

repository used: https://github.com/Luxray5474/useless-mathII-calculators

**Comment by acaudwell** [comment]
What this option does it give the output an alpha channel (which normally isn't useful), so if you take a screenshot for instance, the bloom is translucent. Probably not useful in most cases.

The description could probably be improved.

**Comment by Luxray5474** [comment]
@acaudwell Speaking of the description, I'm actually in the process of making it better. Been doing so slowly for the past few days, making it look prettier and trying my best to include examples for misunderstood commands. Thank you so much for this clarification! :smiley:
