### ISSUE TITLE
Windows filename invalid

### ISSUE THREAD

**Issue by SteamDosh** [acaudwell/Gource#166]
Hi, I think this may have gone unnoticed for a long time however https://github.com/acaudwell/Gource/blob/master/src/formats/commitlog.cpp#L29

Windows files cannot contain question mark characters so usernames with `"` in them become invalid when trying to load an avatar with the same username

ie `apple "von" apple` would become `apple ?von? apple` however `apple ?von? apple.jpg` cannot exist

**Comment by acaudwell** [comment]
Any suggestions for what character it should use on windows instead? maybe `.`?

**Comment by SteamDosh** [comment]
I can't see an issue with using `.` as a replacement

**Comment by david-a-wheeler** [comment]
One challenge: if a filename ends in "." I believe it's a problem in Windows with the normal Windows API.

It's possible to work around this by using the prefix`\\\\?\\ - but that means you have to absolute pathnames and such. See:
https://stackoverflow.com/questions/11681207/how-to-create-a-filename-with-a-trailing-period-in-windows
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

It would probably be simpler to choose a different replacement character or just strip out question marks on Windows platforms.
