### ISSUE TITLE
Enable TLS on gource.io

### ISSUE THREAD

**Issue by bentley** [acaudwell/Gource#169]
Visiting https://gource.io/ leads to a certificate error, as GitHub serves a certificate only valid for GitHub subdomains.

As of May 1, GitHub supports TLS for custom domains by hosting sites on a CDN. This means [updating the DNS records for gource.io](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain) should be enough to enable TLS via Let’s Encrypt.

**Comment by acaudwell** [comment]
Thanks for point this out. I'm working on it.
