### ISSUE TITLE
Conside date_format in the slider

### ISSUE THREAD

**Issue by SmallLars** [acaudwell/Gource#175]
https://github.com/acaudwell/Gource/blob/b49c828a6c1faee225106745eeabce9e7a7caa8b/src/gource.cpp#L281

Maybe it is a good idea to use gGourceSettings.date_format.c_str() here to?

**Comment by acaudwell** [comment]
I'm not sure there is much need to configure this as people don't normally make videos where they interact with the timeline slider. I think the reason it isn't using the same format is because the hour/second granularity looked extraneous.

**Comment by SmallLars** [comment]
hmm.... got it. Thank you.
