### ISSUE TITLE
Gource 0.50

### ISSUE THREAD

**Issue by SmallLars** [acaudwell/Gource#176]
Any idea when 0.50 will be build/published?
Is there a chance #122 and #175 will be solved
and #170 and #174 come in in this version?

**Comment by acaudwell** [comment]
Maybe in October? I will merge the file key option, I was wondering if the command line option could have a different name other than fallback but I couldn't think of one. I'll try and replicate the deletion issue.

**Comment by SmallLars** [comment]
Thank you for the information. It is not important for me to have a fast release. Only wanted to know, how much time is left to discuss new features or fix bugs.

**Comment by SmallLars** [comment]
hmm... Sometimes there are folders without any file. This looks crazy when there are some single empty folders in a row. Java packages are organized in folders, so an example can be org.company.project.main resulting in a single file org/company/project/main.java.

What do you think about a black circle with a white border for empty directories? So no directory is without a (file)circle and a row of empty directories is divided by that circles.

**Comment by SmallLars** [comment]
@acaudwell do you have any idea when you will have time to continue the work on Gource?

**Comment by acaudwell** [comment]
I have a bit more time now to work on it again.
