### ISSUE TITLE
preview doesn't work

### ISSUE THREAD

**Issue by iostyle** [acaudwell/Gource#182]
MacBook Pro

**Comment by iostyle** [comment]
preview doesn't work , but save ppm ➡️ mp4 use ffmpeg is working

**Comment by iostyle** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/22219146/47426816-ef1abe00-d7c0-11e8-8fc5-645574beac81.png">

**Comment by acaudwell** [comment]
What distro did you install gource from or did you build it from source? My guess is could be a problem with SDL2 as it sounds like OpenGL is rendering but its not getting drawn on screen.

**Comment by iostyle** [comment]
brew
