### ISSUE TITLE
doesn't support i18n

### ISSUE THREAD

**Issue by taojintianxia** [acaudwell/Gource#185]
hi , there
  I'm from China, so my locale is "zh-CN" , when I try Gource I got an issue like following screenshot : the date in Chinese turns to messy codes . it should be yyyy年(year)MM月(month)dd日(day) but it display as yyyy口-MM口-dd口
  
![gource-i18n](https://user-images.githubusercontent.com/4112856/49912418-12aadc80-fec5-11e8-9e9a-d2ddf1ec422d.jpg)

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/54798155-3636ad80-4c92-11e9-9950-b45db36593e0.png)

**Comment by acaudwell** [comment]
There is now a `--font-file` option so you can set it to a font with the right character set.
