### ISSUE TITLE
[Feature Request] allow set font, this can make support display chinese too

### ISSUE THREAD

**Issue by bluelovers** [acaudwell/Gource#196]
[Feature Request] allow set font, this can make support display chinese too

i replace the `data\fonts\FreeSans.ttf` to another font

and it can display chinese

so i think we need a option for set font, make it can use another font

if can, hope can support .otf too

![image](https://user-images.githubusercontent.com/167966/55681511-d3b00380-5959-11e9-9d8f-eeef24864f4b.png)

---

* https://github.com/acaudwell/Gource/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+chinese
* https://github.com/acaudwell/Gource/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+i18n
* https://github.com/acaudwell/Gource/issues/185

**Comment by acaudwell** [comment]
I've added a run time option --font-file to gource and also a compile time option --enable-font-file to the configure script.
