### ISSUE TITLE
last commit breaks gource for at least git 2.7.4 (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by SimonAnnetts** [acaudwell/Gource#198]
--no-show-signature is not a valid command line option for git log, certainly for the git version that ships with Ubuntu 16.04 LTS. I also can't find it in the git documentation. Gource fails with:
~~~
gource  .
fatal: unrecognised argument: --no-show-signature
gource: failed to generate log file
Try 'gource --help' for more information.
~~~

**Comment by pzygielo** [comment]
> --no-show-signature...
> I also can't find it in the git documentation. 

https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.10.0.txt

NB - git 2.7.4 is 3+ years old.

**Comment by acaudwell** [comment]
Yeah I wondered if that would cause an issue. I have to check the version number.

**Comment by acaudwell** [comment]
I've made it check the git version.
