### ISSUE TITLE
[Feature Request] Focus on Specific Folder within Repo

### ISSUE THREAD

**Issue by wapisani** [acaudwell/Gource#203]
Is there a way to focus on a specific folder within your repo? If not, I would like to request this feature. Thanks!

**Comment by wapisani** [comment]
I figured out a way to do this. Use the git log command like so: git log --pretty=format:user:%aN%n%ct --reverse --raw --encoding=UTF-8 --no-renames -- Your_Directory_Here > Your_Directory_Here.log. This command would be run from the root of your git repo so the path would need to be from the root.

Then simply do gource ./Your_Directory_Here.log to visualize that directory.

**Comment by sevku** [comment]
Just wanted to make the instruction provided by @wapisani more readable.

1. step
This command would be run from the root of your git repo so the path would need to be from the root.
```bash
git log --pretty=format:user:%aN%n%ct --reverse --raw --encoding=UTF-8 --no-renames -- Your_Directory_Here > Your_Directory_Here.log
```
2. step
Then simply do `gource ./Your_Directory_Here.log` to visualize that directory.
