### ISSUE TITLE
some parameter let gource crash

### ISSUE THREAD

**Issue by peterdd** [acaudwell/Gource#204]
Some parameter I tried do not work and let gource crash:
 
```bash
>gource -s 1
>gource -s 0.1
libc++abi.dylib: terminating with uncaught exception of type ConfFileException: invalid 'seconds-per-day' value
Abort trap: 6
>gource -s .1
libc++abi.dylib: terminating with uncaught exception of type ConfFileException: invalid 'seconds-per-day' value
Abort trap: 6
>gource -s 1/10
>gource -p 0.8
libc++abi.dylib: terminating with uncaught exception of type ConfFileException: start-position outside of range 0.0 - 1.0 (non-inclusive)
Abort trap: 6
>gource -p 0.6-0.8
libc++abi.dylib: terminating with uncaught exception of type ConfFileException: start-position outside of range 0.0 - 1.0 (non-inclusive)
Abort trap: 6
>gource -p random
>gource -p .8
libc++abi.dylib: terminating with uncaught exception of type ConfFileException: start-position outside of range 0.0 - 1.0 (non-inclusive)
Abort trap: 6
```

installed v0.49 with `brew install gource` (on a mac)

**Comment by acaudwell** [comment]
The exception should be being caught being caught by the try in main.cpp, I think it might be a homebrew issue.

Dunno why its not accepting the decimals.

**Comment by Cartoonman** [comment]
FWIW I ran gource which was installed via brew on OSX 10.14 and did not encounter this issue.

**Comment by peterdd** [comment]
OSX 10.13.6 

Tried today again, same errors. gource says its version 0.49

Then run `brew upgrade ` and **after that gource works also with the parameters**.

So maybe some dependency libs were upgraded/fixed? 
For instance 

```
:~>brew upgrade
==> Upgrading 30 outdated packages:
gtk+ 2.24.32_2 -> 2.24.32_3
wget 1.20.3 -> 1.20.3_1
libidn2 2.1.1a -> 2.2.0_1
boost 1.70.0 -> 1.71.0
pango 1.42.4_1 -> 1.44.7
nano 4.3 -> 4.5
gdk-pixbuf 2.38.1 -> 2.40.0
atk 2.32.0 -> 2.34.1
harfbuzz 2.4.0_1 -> 2.6.2
glib 2.62.0_1 -> 2.62.2
...
```

**Comment by Cartoonman** [comment]
Likely the glib version was mismatched (in the list of packages you posted). Surprised that brew didn't catch the dependency mismatch when gource was installed though. Glad it worked out!
