### ISSUE TITLE
[Request] Hide files and directories by name

### ISSUE THREAD

**Issue by QuantumCoded** [acaudwell/Gource#207]
I'm not sure if the ability to do this exists, but would it be possible to add the ability to hide a specific file or directory throughout the visualization. I'm having a problem where a large directory is shown taking up most of the screen, even though it's mainly just assets and nothing interesting happens with it. It would be nice to be able to tell it not to render that directory allowing for an easier time viewing all the important things that are going on.

**Comment by acaudwell** [comment]
Hi. The --file-filter option excludes file paths so you can match the directory you don't want to show.

**Comment by QuantumCoded** [comment]
Thanks! Helped a ton.
