### ISSUE TITLE
Segmentation Fault 11 when using --user-image-dir on Mac OS Mojave

### ISSUE THREAD

**Issue by textarcana** [acaudwell/Gource#208]
As of version 0.49, using the `--user-image-dir` option results in a segmentation fault on Mac OSX Mojave.

I just tried 0.48 and it does not segfault.

This is what happens when I try to use 0.49:

```
$ ls avatar/
'Noah Sussman.png'  'Noah Sussman New Media, LLC.png'

$ gource --user-image-dir avatar
Segmentation fault: 11
```

**Comment by raftalks** [comment]
I came across this issue and managed to work around this by reinstalling with the following command on mac
```brew rm gource && brew install -s gource```
