### ISSUE TITLE
font-file not recognised in 0.49

### ISSUE THREAD

**Issue by catchingknives** [acaudwell/Gource#211]
I installed `gource` using `brew` and am running 0.49

```
$ gource --help
Gource v0.49
```

but `font-file` isn't recognised. The error is

```
gource: unknown option font-file
```

**Comment by mschilli87** [comment]
@catchingknives: Do you have the output of the `brew` command?

A [quick search on github](https://github.com/acaudwell/Gource/search?q=font-file&type=Code) followed by [one on DDG](https://duckduckgo.com/?q=ac_arg_enable&ia=web) (leading [here](https://autotools.io/autoconf/arguments.html)) revealed that the `font-file` option seems to be optional so you might have the specify `--enable-font-file` at configure time:

https://github.com/acaudwell/Gource/blob/93b5210e3809ff95b5ba50a13a84e42097573ae8/configure.ac#L56

**Comment by catchingknives** [comment]
I do but I don't think it helps much. If it's optional I guess it depends how the binary which has been put in `brew` was compiled. 

```
$ brew install gource

==> Installing dependencies for gource: glew and sdl2_image
==> Installing gource dependency: glew
==> Downloading https://homebrew.bintray.com/bottles/glew-2.1.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a8/a81e04f8be35080991e136e0b2229448fd237a31991d34d5a2e1c5f8db795201?__gd
######################################################################## 100.0%
==> Pouring glew-2.1.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/glew/2.1.0: 38 files, 3MB
==> Installing gource dependency: sdl2_image
==> Downloading https://homebrew.bintray.com/bottles/sdl2_image-2.0.5.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sdl2_image-2.0.5.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/sdl2_image/2.0.5: 10 files, 278KB
==> Installing gource
==> Downloading https://homebrew.bintray.com/bottles/gource-0.49.mojave.bottle.1.tar.gz
==> Downloading from https://akamai.bintray.com/f7/f7b1c895b7c202aae26d1396b2634082ede889eb5c9bf0b2d7758e52f88c924e?__gd
######################################################################## 100.0%
==> Pouring gource-0.49.mojave.bottle.1.tar.gz
🍺  /usr/local/Cellar/gource/0.49: 21 files, 2.0MB
```

**Comment by acaudwell** [comment]
Hi. The font-file option isn't in a released version yet. Passing --HEAD to brew will make it try to install the development version.

Let me know if you have any issues with --font-file option if you try it out.

**Comment by catchingknives** [comment]
@acaudwell Thanks! Got it running with the `--HEAD` parameter and it works as expected :)
