### ISSUE TITLE
What happened to user-scale?

### ISSUE THREAD

**Issue by david-a-wheeler** [acaudwell/Gource#217]
The README documents `--user-scale SCALE` : "Change scale of user avatars.".  It used to work.

However, the latest build doesn't have the option - I get gource: unknown option user-scale=9.0.

Can this capability be easily restored?  My guess is that it disappeared by accident.

**Comment by acaudwell** [comment]
I think its a command line syntax issue? The gource command line parser doesn't handle specifying a value using equals (=). `--user-scale 9` works for me.

**Comment by david-a-wheeler** [comment]
Ah, thanks!
