### ISSUE TITLE
Support ISO 8601 datetimes (YYYY-MM-DD[Thh:mm[:ss]]) in custom log format and captions

### ISSUE THREAD

**Issue by david-a-wheeler** [acaudwell/Gource#220]
The [custom log format](https://github.com/acaudwell/Gource/wiki/Custom-Log-Format) and [captions](https://github.com/acaudwell/Gource/wiki/Captions) use Unix timestamps, which aren't user-friendly.

I propose that the reader check if "-" is in the time, and if so, interpret the time as an ISO 8601 format datetime per [W3C Note-datetime](https://www.w3.org/TR/NOTE-datetime). That is, "YYYY-MM-DD" optionally followed by "Thh:mm[:ss][offset]".

**Comment by acaudwell** [comment]
Good suggestion. I had the same thought last time I pointed someone to it.

**Comment by ayeseeem** [comment]
I think this can be closed: I think both custom log format and captions now support ISO 8601:

searching <https://github.com/search?q=repo%3Aacaudwell%2FGource+8601&type=commits> gives these commits:

- 127a30bf6a32238d0f5774acab0b6f2c3464f182
- 134a0a64877e37d717d771f88bf6b729af38e7ad

**Comment by david-a-wheeler** [comment]
If so, that's great! Thank you!
