### ISSUE TITLE
Changing the font sizes of filenames and directory names

### ISSUE THREAD

**Issue by lzkSteven** [acaudwell/Gource#222]
The following commands are mentioned in the README:
  --font-scale SCALE
            Scale the size of all fonts.
    --font-size SIZE
            Font size used by the date and title.
    --file-font-size SIZE
            Font size of filenames.
    --dir-font-size SIZE
            Font size of directory names
    --user-font-size SIZE
            Font size of user names.
But none of these work except --font-size, which only changes the font size of the date shown on the top and the title.

**Comment by acaudwell** [comment]
Those features aren't in a released version yet.

**Comment by lzkSteven** [comment]
Thanks!

**Comment by 1138-4EB** [comment]
@acaudwell, is there any plan to release a new version in the following months?

**Comment by acaudwell** [comment]
Yep I'm working on it.
