### ISSUE TITLE
New Versions Not in Homebrew?

### ISSUE THREAD

**Issue by geoffreywiseman** [acaudwell/Gource#225]
Hey, just installed Gource on a new Mac, had some issues, and wondered if I had the latest -- looks like the Homebrew formula is still on v0.49?

**Comment by acaudwell** [comment]
Someone just needs to update the gource.rb formula to use 0.51. Or just install it using the `--HEAD` option and it will get the current development version.

**Comment by geoffreywiseman** [comment]
I wasn't sure if you were the one maintaining the formula, guess not -- I'll do my first `brew bump-formula-pr` then.  Thanks!
