### ISSUE TITLE
[feature request] Many repositories visualization

### ISSUE THREAD

**Issue by GlebZemnieks** [acaudwell/Gource#230]
Intro:
A project with microservice architecture. 12 repositories. 

actual: 
Can't visualize all activity for all repositories. Only one repo and then have the necessity to combine rendered video to one file by video redactor. 
And I can’t do video well with multi repositories timing scaling and consolidation by hand. 

expected:
List of .git folders input. Independent visualization for each.

**Comment by mastercoms** [comment]
https://github.com/acaudwell/Gource/wiki/Visualizing-Multiple-Repositories

**Comment by volkert-fastned** [comment]
First of all: what an amazing tool! Thanks for sharing this with the world.

> https://github.com/acaudwell/Gource/wiki/Visualizing-Multiple-Repositories

That works, thanks.

But is there a way to have the repositories spread out further? they tend to stay clumped together around the center too much, without taking any advantage of the available real estate towards the sides of the screen. That makes it less clear that these are separate projects that are simultaneously being worked on.

In general, it appears that the height of the screen is being utilized optimally, but the width of the screen not so much. Is there any way to tweak this?

If you prefer, I can create a separate issue for this.
