### ISSUE TITLE
--user-image-dir not working

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [acaudwell/Gource#231]
Hi there,

And thanks for this beautifull tool.

I am trying to use the option :
`gource --user-image-dir .git/avatar/`

But the icon don't appear, can i debug this and how ? Do i need all the pictures of all the users of the repo to use it ?
Of course i put all the pictures on the .git/avatar folder

I tried also --default-user-image and it worked

**Comment by acaudwell** [comment]
Most likely the names on the images don't match the user names (if it was a problem loading the image you should get an error).

Do the user names have non-ascii characters?

What version of Gource and platform are you using?

**Comment by Jacques-Olivier-Farcy** [comment]
Hi Andrew,

Thanks, i will check that.
I am on Linux Mint 19.3
Gource 0.47-1

**Comment by Jacques-Olivier-Farcy** [comment]
Hi Andrew,

Thanks, i checked the names, it works now, thanks !

**Comment by Jacques-Olivier-Farcy** [comment]
Solved
