### ISSUE TITLE
[feature] Use filename font size setting for file key font size

### ISSUE THREAD

**Issue by 0jrp0** [acaudwell/Gource#243]
https://github.com/acaudwell/Gource/blob/93b5210e3809ff95b5ba50a13a84e42097573ae8/src/key.cpp#L166

The above code should use filename font size to grab the appropriately sized font rather than a hard coded value. When creating 4k videos using 3840x2160 resolution, the fonts become unreadable. To solve this, a user can pass --font-scale 2 in and get the desired effect. However, the file key does not reference the scaling parameter and so the file key is unreadable at 4k resolution. The idea will be to reuse the filename font size parameter for the key, rather than create another parameter for it. This would also then reference the font scale parameter.

**Comment by acaudwell** [comment]
Good point. `--font-scale` now also scales the font key.
