### ISSUE TITLE
I'm duplicated

### ISSUE THREAD

**Issue by donno2048** [acaudwell/Gource#246]
My username is (as you can see) donno2048 and my name is Elisha Hollander.
Why is that important?
Because when I use Gource on [my project](https://github.com/donno2048/CITUR-L) I see a user named donno2048 and **another one** named Elisha Hollander
<img width="202" alt="Screenshot 2020-09-23 192912" src="https://user-images.githubusercontent.com/61805754/94041954-99e3ee80-fdd3-11ea-8abf-3fb793b98ab5.png">

**Comment by mschilli87** [comment]
I cloned your repo and did a quick check:

```sh
git log --format='%an <%ae>' | sort | uniq -c | sort -k1,1nr
```

Turns out you used differen names and emails for different commits:

```
  65278 donno2048 <just4now666666@gmail.com>
    116 donno2048 <61805754+donno2048@users.noreply.github.com>
     79 Elisha Hollander <just4now666666@gmail.com>
      1 username669 <68505982+username669@users.noreply.github.com>
```

So while GitHub knows the first three identities all belong to the same user, Git and thus Gource cannot know that.

**Comment by donno2048** [comment]
Thanks!

**Comment by donno2048** [comment]
Actually it still not working

**Comment by donno2048** [comment]
It was because I added another file with this code...
