### ISSUE TITLE
[IDEA] Option to make caption disapear instead of stacking

### ISSUE THREAD

**Issue by Seluj78** [acaudwell/Gource#250]
Hi ! I loooooove gource and I just discovered captions after 2 and a half years of using it to show off 😎 

I have a feature request for the captions, as I would like to show the git log as the days go, Would it be possible to add an option that would make the captions replace one another instead of stacking ?

To avoid:

![Screenshot 2020-10-28 at 16 18 51](https://user-images.githubusercontent.com/4641317/97456566-48ca9b80-1939-11eb-922d-81e736eb1194.png)

Thanks again for the amazing work

**Comment by Seluj78** [comment]
PS: Setting the `caption-duration` almost acheives the desired effect but some are still stacked over one another

**Comment by 0jrp0** [comment]
You might want to reconsider having so many captions show up in a short timespan. Even if there were a parameter that swapped it out quickly, I think it'd become unreadable at that point. I recommend cutting down the # of captions, shorten duration, and space them out appropriately.

**Comment by Seluj78** [comment]
@0jrp0 I agree, I might need to reduce the amount of commits I show, but I still think it'd be useful to have that as a feature 👍

**Comment by NeilCross** [comment]
Would it be possible to control the display of a captions based on the commit id? i.e. to provide a file of commit ids you wanted captions to show for?
