### ISSUE TITLE
I can't seem to add profile images.

### ISSUE THREAD

**Issue by Robatortas** [acaudwell/Gource#271]
I dont know how to make profile pictures appear on the person who is editiing the graph, I know we need to use gravatar. But I don't seem to find a way to make this run with custom profile pictures.

**Comment by acaudwell** [comment]
Hi. It doesn't have to be from Gravatar (or you can add to or replace the images that were downloaded from Gravatar).

You make a directory with images with the same name as users in your repo.
E.g. `John Smith.png` (or `.jpg`) to make an image for the user `John Smith`.

Then run gource with `--user-image-dir IMAGE_DIRECTORY` to tell it where to look for the images.

**Comment by Robatortas** [comment]
Yeah, thanks for the reply! I already saw on how to fix it. Thank you very much for taking your time. Great work this project has!

**Comment by NikosAlexandris** [comment]
> Hi. It doesn't have to be from Gravatar (or you can add to or replace the images that were downloaded from Gravatar).
> 
> You make a directory with images with the same name as users in your repo. E.g. `John Smith.png` (or `.jpg`) to make an image for the user `John Smith`.
> 
> Then run gource with `--user-image-dir IMAGE_DIRECTORY` to tell it where to look for the images.

Version 0.56 with `gource -H` shows 

``` bash
  --user-image-dir DIRECTORY       Dir containing images to use as avatars
```

This didn't help me understand how to connect images with avatars shown. I compiled gource from source just yesterday. However, there is also this [            (eg "Full Name.png") to use as avatars.](https://github.com/acaudwell/Gource/blame/master/README.md#L235) shown in the `README.md` file. So I am digging in the issues to understand what and how. Is this in need for a fix ?
