### ISSUE TITLE
Font size only applies to date and time and does not scale with resolution

### ISSUE THREAD

**Issue by KonradHoeffner** [acaudwell/Gource#277]
There are two problems with the font-size that both make the text too small to read on high resolutions such as 3840x2160 (4k):

1. The font size does not scale with resolution. So if I create a 4k video and upload it on YouTube and the users watch it in 720p, they cannot read anything.
2. The font size parameter --font-size only applies to the date and time at the top, so there is no way to manually increase the font size of the text in edges of the graph and the user names.

## Minimum Working Example

Use any repository and compare:

* gource -320x200 --font-size 1
* gource -3840x2160 --font-size 1
* gource -320x200 --font-size 100 
 ![gource-320-200-font-size-1](https://user-images.githubusercontent.com/839577/149361354-9cb81c04-f43e-41fa-95e3-e9c2a067a9bb.png)
* gource -3840x2160 --font-size 100

![gource-3840-2160-font-size-100](https://user-images.githubusercontent.com/839577/149361927-7f0f3273-4f4f-4ebb-8d63-0885b5e0b8b1.png)

**Comment by acaudwell** [comment]
FYI 0.52 (will be released soon, can be built from git) has more font-size command options and also fixes some issues with the `--font-scale` option which is probably want to use for 4K.
