### ISSUE TITLE
Does not play in native resolution (4K)

### ISSUE THREAD

**Issue by Ozzah** [acaudwell/Gource#280]
I'm running Gource 0.51 built from source on WSL2 using X410 on Windows 10 19043.1466 on a NVidia RTX 2080 Super with GeForce Game Ready Driver 471.96, and I am running dual 4K monitors at native resolution.

Gource seems to work fine with various settings at various resolutions, however when as I set the resolution to 4K using `-3840x2160` switch, the Gource window appears but the timeline does not play. If I set it to `-3839x2159` or `-3841x2161` it does play.

**Comment by acaudwell** [comment]
Interesting to know that it builds ok on WSL2.

What do you actually see when it runs? Maybe you can post some screenshots.

Does it behave differently with the `-f` flag?

Does the binary release of gource 0.51 behave differently?

I suspect this might be a High DPI thing, which I probably should add at least a command line flag for overriding the behaviour, though might be complicated by WSL2.

**Comment by acaudwell** [comment]
Think I may have fixed it:
https://github.com/acaudwell/Gource/commit/0419ef146878958c74cc9c520891fe14aac4c789

Tested it with using Nvidia `DSR Factor` display setting to simulate a 4K display.

On my TV there are some odd bloom radial artifacts that I couldn't determine the cause of, and they didn't appear in screenshots taken using `DSR Factor` scaling, so I wonder if the display itself was the issue... perhaps its a high dynamic range thing.

**Comment by Ozzah** [comment]
I just recompiled from source and tested it on WSL2 with X410, and can confirm that both `-f` and `-3840x2160` now appear to work properly. Thanks @acaudwell!
