### ISSUE TITLE
[Feature] customize log command

### ISSUE THREAD

**Issue by delanym** [acaudwell/Gource#281]
The command

    gource --log-command git

gives

    git log --pretty=format:user:%aN%n%ct --reverse --raw --encoding=UTF-8 --no-renames --no-show-signature

and I want it to be

    git log --pretty=format:user:%aN%n%ct --reverse --raw --encoding=UTF-8 --no-renames --no-show-signature --all

How can I do that?

**Comment by acaudwell** [comment]
If you add `--output log.txt` to the `git log` command and make any other changes you want and run it (provided you don't change the format), it'll write the output to `log.txt`, you can then run `gource log.txt`.
