### ISSUE TITLE
blurry on high resolution screen

### ISSUE THREAD

**Issue by verhovsky** [acaudwell/Gource#284]
I have a macbook air, the screen is 2560 × 1600 pixels, but in most things (like in the browser for example) it's detected as 1280 × 800, including by gource it seems. It's still visibly low resolution if I set the resolution to `-2560x1600`.

**Comment by acaudwell** [comment]
If you install it using `brew install --head gource` (assuming you installed it using homebrew) it might fix the resolution issue as I recently made a change to attempt to fix that.

Curious to hear if it does or not.

**Comment by verhovsky** [comment]
I get this error running that command

```
checking pkg-config is at least version 0.9.0... yes
checking for FT2... yes
checking for PCRE2... configure: error: Package requirements (libpcre2-8) were not met:

No package 'libpcre2-8' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PCRE2_CFLAGS
and PCRE2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by verhovsky** [comment]
After editing the formula to use `pcre2`, I can install it and it's using the correct pixel resolution now, however all the text is really small.

**Comment by acaudwell** [comment]
Good to know it works!

I did make it scale the fonts if the resolution is over 4k (3840 x 2160), but not currently on 2560x1600. There is a `--font-scale` option that you can manually adjust the ratio with.
