### ISSUE TITLE
docs don't explain what "time scale" is

### ISSUE THREAD

**Issue by verhovsky** [acaudwell/Gource#285]
This:

```
    -s, --seconds-per-day SECONDS
            Speed of simulation in seconds per day.

    -c, --time-scale SCALE
            Change simulation time scale.
```

doesn't explain what "time scale" is and how it's different from speed. The clarifying text "Change simulation time scale" doesn't clarify anything if you don't already understand what the argument does from its name.

Thanks for the great tool! Also, it would be nice if pressing `?` in the video would show a list of all the shortcuts.

**Comment by paul-uz** [comment]
Did you try it?

I did, and it seems to be just an arbitary speed multiplier. A time scale fo 4 is faster than a time scale of 1 for example.

**Comment by acaudwell** [comment]
Ok I've now added an example to the docs.
