### ISSUE TITLE
Hovering over the end of the timeline breaks playback

### ISSUE THREAD

**Issue by codl** [acaudwell/Gource#288]
At the rightmost edge of the timeline there is an area that, if hovered, does not show a date but still stops the timeline from fading away

If time is advancing while the mouse cursor is on this area, and time auto skips forward, then playback stops immediately after the time skip and can only be resumed by seeking by clicking somewhere on the timeline (pressing space does nothing)

Gource v0.52 on Linux

**Comment by acaudwell** [comment]
Thanks. I think I've fixed this now.

**Comment by codl** [comment]
Can confirm, I can't reproduce the issue anymore after building from 8060988
