### ISSUE TITLE
Wiki > Videos: Incorrect markdown for link

### ISSUE THREAD

**Issue by jawn** [acaudwell/Gource#295]
Page: https://github.com/acaudwell/Gource/wiki/Videos

The link to Open Broadcaster Software is shown as markdown:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/1705112/195305617-462ffa54-406a-4017-bbeb-430e00d034f5.png">

Probably due to space between [] and ()

**Comment by acaudwell** [comment]
Fixed. Thanks for pointing that out.
