### ISSUE TITLE
CJK support

### ISSUE THREAD

**Issue by wybert** [acaudwell/Gource#296]
I am using `gource my-project-custom.log  --caption-file commitmsg.txt ` to visualize my repo changes.   `commitmsg.txt` has some Chinese characters, and these words did not show correctly (see below).

<img width="994" alt="image" src="https://user-images.githubusercontent.com/5254627/197438742-4705c483-00ad-4c09-8f24-5cf0584c628c.png">

**Comment by acaudwell** [comment]
You can specify a different font with the `--font-file` option that includes CJK characters.

**Comment by wybert** [comment]
> You can specify a different font with the `--font-file` option that includes CJK characters.

Yes. It works
