### ISSUE TITLE
Is Gource safe to use on private repos?

### ISSUE THREAD

**Issue by sheldonreddy** [acaudwell/Gource#298]
I'd love to run Gource on a private repo which has a lot of intellectual property and many devs contributing. 

Needless to say, it would be a disaster if any of the source code was exposed publicly due to Gource. 

I'd like to confirm Gource does not expose any data from private repos.

Thanks

**Comment by hervelemeur** [comment]
Just for the sake of it, in the generated video folders, filenames, authors and dates are potentially exposed.

**Comment by sheldonreddy** [comment]
@hervelemeur @mschilli87 Thank you for your responses and the suggestion - definitely will be going the route of running it on an isolated machine. Not too phased about the video data as I won't be distributing it - only using it in a video but I am glad I can annonymise it if need be :)

Thanks all - appreciate it!

**Comment by acaudwell** [comment]
Just for the record, Gource just runs the `git log` command to get the history, and it doesn't do any network requests.

E.g. if you want to fetch gravatars of your users you need to do that yourself.
