### ISSUE TITLE
Feature request: Option to hide/exclude certain directories from output.

### ISSUE THREAD

**Issue by Ben-Fenner** [acaudwell/Gource#304]
I'm loving this project and running it on our main Ruby on Rails repo right now.

I would love the option to exclude a certain directory (or directories) from the output (log file?).
In many Ruby on Rails projects, the public assets directory is enormous, and gets updated all at once, sometimes very often. This can dwarf the rest of the project, and in many ways is just noise. I'd love to be able to make visualizations that exclude this directory.

Anyway, I'm still getting a lot out of this tool. Thank you!

**Comment by acaudwell** [comment]
Thanks. `--file-filter REGEX` can be used to match and filter out certain files and directories.

**Comment by Ben-Fenner** [comment]
Excellent!
Is that something that should be added to the docs, or did I just completely miss it?
