### ISSUE TITLE
How to always show directory names

### ISSUE THREAD

**Issue by adamency** [acaudwell/Gource#309]
I want to be able to have all directory names keep being displayed during the entire video, while having the file names appear and fade out as usual.

For this I've found two options

`----file-idle-time`

and 

`--filename-time`

Talking now only about names (not the nodes and vertices), with `--filename-time 0` files keep displayed during the entire video, but directories fade out. Whereas I want the opposite. I've looked in the manual and there doesn't seem to be an equivalent for directories like `--directory-name-time` and I haven't been able to understand what `--file-idle-time` actually does.

I have found Issue #215 which mentions `-hide filenames` but this completely turns off filenames and I would like to still see them a short time when the files first appear.

Basicall the wished behavior is the opposite of using `gource` with `--filename-time 0` only (which would be `files <persistent> directory <ephemeral>`) => 

```
file <ephemeral> directory <persistent>
```

Is this possible currently with gource ? If not, could you point me towards the bit of code that handles this if you don't mind so that I could try making a modification myself ?

Thanks in advance

**Comment by acaudwell** [comment]
Hi. I think `--highlight-dirs` does what you want.

**Comment by adamency** [comment]
@acaudwell Yup ! I ended up finding it and it does indeed exactly what I want :) thank you all the same !
