### ISSUE TITLE
feature request: ignoring a particular folder

### ISSUE THREAD

**Issue by kevgo** [acaudwell/Gource#319]
My codebase uses vendored dependencies, i.e. I download the source code of external libraries that I use and store it in a folder called "vendor". It would be great if I could exclude this entire folder from the visualization. Reasons are that the dependencies dominate much of the screen, don't update often, and don't contain the type of hands-on development work I want to visualize for my project. Thanks! 🙏

**Comment by kevgo** [comment]
Workaround to remove the "vendor" folder from all commits until this is implemented properly in gource itself:

- create a copy of your repo (you are going to throw away parts of the repo, don't do this on the original repo!)
- run `git filter-branch --tree-filter 'rm -rf vendor' HEAD`
- this rewrites all commits to not contain the "vendor" folder
- run gource as usual

**Comment by acaudwell** [comment]
Hi. `--file-filter REGEX` can be used to match and filter out directories.

**Comment by kevgo** [comment]
Thanks! I didn't see this option documented at https://github.com/acaudwell/Gource/wiki/Controls, and also not when running `gource -h`. 

I just found it documented in https://github.com/acaudwell/Gource/blob/master/README.md.
