### ISSUE TITLE
Code is not shown in chronological order.

### ISSUE THREAD

**Issue by dchokola** [acaudwell/Gource#32]
Example video:
https://youtu.be/r7JMrg1zcSs?t=47s
Goes through July, August, then May, June, July...
This has the unfortunate side effect of making all the captions display at the same timestamp (in May 2005). The first timestamp is actually for Dec 18, 2005.

**Comment by acaudwell** [comment]
The time travel event is probably a branch being merged in. I hadn't considered the interaction that would have with captions.

Gource doesn't sort the log file generated by the version control system specific history log command (I suppose it could, it would just take longer to load).

You can work around this by sorting the log file on date before handing it to gource. You can generate an easily sortable file with the --output-custom-log FILE option.

**Comment by SmallLars** [comment]
Should be solved by #171.
