### ISSUE TITLE
README doc seems to be incorrect. Plus/minus don't adjust simulation speed, they zoom in/out.

### ISSUE THREAD

**Issue by Ben-Fenner** [acaudwell/Gource#322]
I've been enjoying this tool for a while. I ran it about a year ago and it changed priorities for me, which was excellent.
I'm running it again about a year later and just happened to notice the README documentation for keyboard shortcuts says:
`(+-)  Adjust simulation speed`

However those keyboard buttons seem to zoom the display instead. Not sure if the docs need updating, or if the simulation speed keybindings need updating, but there you are.

For now the only way I seem to be able to adjust what feels like the simulation speed seems to be with:
`(<>)  Adjust time scale`

Oh yah, I forgot to mention I'm running the latest release version (`0.54`).

Cheers!

**Comment by acaudwell** [comment]
The Keypad +/- keys zoom in and out, but this wasn't documented so I have updated the README.
