### ISSUE TITLE
Install failed on M1, error: use of undeclared identifier 'extension'

### ISSUE THREAD

**Issue by xuchen81** [acaudwell/Gource#328]
I am building on Mac Book Pro M1, 14.1.1, getting this error: error: use of undeclared identifier 'extension'
`
└─[0] <> make
g++ -DPACKAGE_NAME=\"Gource\" -DPACKAGE_TARNAME=\"gource\" -DPACKAGE_VERSION=\"0.54\" -DPACKAGE_STRING=\"Gource\ 0.54\" -DPACKAGE_BUGREPORT=\"acaudwell@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"gource\" -DVERSION=\"0.54\" -DHAVE_TIMEGM=1 -DHAVE_UNSETENV=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_OPENGL_GL_H=1 -DHAVE_GL=1 -DHAVE_OPENGL_GLU_H=1 -DHAVE_GLU=1 -DHAVE_IMG_LOADPNG_RW=1 -DHAVE_IMG_LOADJPG_RW=1 -DHAVE_BOOST=/\*\*/ -I.  -DSDLAPP_RESOURCE_DIR=\"/usr/local/share/gource\"   -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/Cellar/pcre2/10.43/include -I/opt/homebrew/Cellar/glew/2.2.0_1/include -DHWY_SHARED_DEFINE -DAVIF_DLL -D_THREAD_SAFE -I/opt/homebrew/include/SDL2 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/Cellar/jpeg-xl/0.10.2/include -I/opt/homebrew/Cellar/highway/1.2.0/include -I/opt/homebrew/Cellar/brotli/1.1.0/include -I/opt/homebrew/Cellar/jpeg-xl/0.10.2/include -I/opt/homebrew/Cellar/little-cms2/2.16/include -I/opt/homebrew/Cellar/libtiff/4.6.0/include -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/Cellar/xz/5.4.6/include -I/opt/homebrew/Cellar/jpeg-turbo/3.0.3/include -I/opt/homebrew/Cellar/libavif/1.0.4/include -I/opt/homebrew/Cellar/webp/1.4.0/include -I/opt/homebrew/Cellar/webp/1.4.0/include/webp -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/include -std=gnu++0x -Wall -Wno-sign-compare -Wno-reorder -Wno-unused-but-set-variable -Wno-unused-variable -g -O2   -MT src/gource-gource_settings.o -MD -MP -MF src/.deps/gource-gource_settings.Tpo -c -o src/gource-gource_settings.o `test -f 'src/gource_settings.cpp' || echo './'`src/gource_settings.cpp
src/gource_settings.cpp:836:36: error: use of undeclared identifier 'extension'
            std::string file_ext = extension(p);
                                   ^
1 error generated.
make: *** [src/gource-gource_settings.o] Error 1
`

**Comment by acaudwell** [comment]
I think this is fixed on master. If you are using homebrew, try `brew install gource --HEAD`
