### ISSUE TITLE
show directory names at nodes

### ISSUE THREAD

**Issue by nschloe** [acaudwell/Gource#33]
I see that directory names appears as labels along the _edges_ leading to the respective directory node.
![edge](https://cloud.githubusercontent.com/assets/181628/9488805/aac95b8a-4bdc-11e5-8113-feb2abfdda46.png)
This gets a little dense when there are many directories originating from the root directory. Is there a way to put the directory names at the directory node?
![edge2](https://cloud.githubusercontent.com/assets/181628/9489001/11f1c3fa-4bde-11e5-9796-1bb9c37c44e5.png)
(I feel this is where they belong to anyways.)

**Comment by acaudwell** [comment]
Initially I had dir names appearing at the centre of the node and then changed them to be drawn at the mid point of the spline (e25b02ddf2e630ad29df29fa42052e25d1a60cba is the commit if you modify your copy of Gource). I think I prefer it as its easier to see what the hierarchy of directories is, IMO (eg 'all this stuff up here is under the zoltan directory').

**Comment by nschloe** [comment]
> I think I prefer it as its easier to see what the hierarchy of directories is, IMO

If you consider more nodes around a center node, it can easily be argued that the visibility is improved if the labels are further apart, e.g.,
![shot](https://cloud.githubusercontent.com/assets/181628/9600635/6ffd357a-509c-11e5-9e9d-23bdc61dbd4e.png)

In any case, could we make this an option for Gource?

> eg 'all this stuff up here is under the zoltan directory').

This would still apply if the labels are drawn next to the nodes.

**Comment by acaudwell** [comment]
I'm open to it being made an option.

**Comment by nschloe** [comment]
I've got it working on https://github.com/nschloe/Gource/tree/dirnames-endpoint; now I just have to figure out how options are parsed. I'll file a PR once this is ready.
