### ISSUE TITLE
OS X Support?

### ISSUE THREAD

**Issue by thinsoldier** [acaudwell/Gource#37]
brew install gource

Installer can't find GLM dependency.

**Comment by acaudwell** [comment]
This sounds like a packaging issue rather than a Gource upstream issue. You should raise this as an issue with the gource package in homebrew if it's a valid issue.

**Comment by jpmhouston** [comment]
I would suggest reopening this issue. Many homebrew users don't like to use it to install desktop applications, only Terminal stuff. You should ask the community for someone wiling to do official Mac builds and host them on your site, or at least link to them.
