### ISSUE TITLE
Build problem on Ubuntu 15.04 - lGLU

### ISSUE THREAD

**Issue by samuelcolvin** [acaudwell/Gource#39]
gsource looks really cool, I saw it from a post on a flask discussion this morning and tried to install it, but ran into problems.

I'm running `./configure` in the directory extracted from the `gource-0.42.tar.gz` file downloaded from the site.

I installed all the dependencies in `INSTALL` as far as I could tell. (the bracketed names all install directly with `apt-get` - maybe it would be worth adding the required apt-get statement to INSTALL?).

The end of the `./configure` output is 
```
checking for GL/gl.h... yes
checking for OpenGL/gl.h... no
checking for OpenGL library... -lGL
checking for GL/glu.h... yes
checking for OpenGL/glu.h... no
checking for OpenGL Utility library... -lGLU
checking for varargs GLU tesselator callback function type... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FT2... yes
checking for PCRE... yes
checking for GLEW... yes
checking for SDL2... yes
checking for PNG... yes
checking for IMG_LoadPNG_RW... yes
checking for IMG_LoadJPG_RW... yes
checking for boostlib >= 1.46... yes
checking whether the Boost::System library is available... yes
checking whether the Boost::Filesystem library is available... yes
configure: error: Could not link against -lGLU !
```

I tried installing and reinstalling the following as these were the suggestions from an extended google of the problem:

    libgl1-mesa-dev libglu1-mesa-dev freeglut3 freeglut3-dev binutils-gold

But still no cigar, same problem. What am I doing wrong?

(if it's relevent I have an nvidia graphics card)

**Comment by samuelcolvin** [comment]
Humm, just cloned master, ran `./autoconf.sh` and it worked fine, maybe worth saying that on ubuntu at least that's the easiest way of installing?

**Comment by acaudwell** [comment]
Yep this is due to a bug in the Boost version detection on Ubuntu/Debian multi-arch systems that causes the misleading message about -lGLU. It's fixed in 0.43 so I should just get around to making that the official release.

Btw there is a gource 0.42 package in Ubuntu.

**Comment by acaudwell** [comment]
Oh wait, 0.43 is the current release linked on the homepage.

There's just no 0.43 for WIndows as the fix only affected Linux configure script.

**Comment by KleinerKobold** [comment]
I got the same problem in current version 0.45, I am running a raspberry pi with NOOBs System

**Comment by KleinerKobold** [comment]
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for timegm... yes
checking for unsetenv... yes
checking how to run the C++ preprocessor... g++ -E
checking for X... libraries , headers 
checking for a sed that does not truncate output... /bin/sed
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether we are using the Microsoft C compiler... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for GL/gl.h... yes
checking for OpenGL/gl.h... no
checking for OpenGL library... -lGL
checking for GL/glu.h... yes
checking for OpenGL/glu.h... no
checking for OpenGL Utility library... -lGLU
checking for varargs GLU tesselator callback function type... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FT2... yes
checking for PCRE... yes
checking for GLEW... yes
checking for SDL2... yes
checking for PNG... yes
checking for IMG_LoadPNG_RW... yes
checking for IMG_LoadJPG_RW... yes
checking for boostlib >= 1.46... yes
checking whether the Boost::System library is available... yes
checking whether the Boost::Filesystem library is available... yes
configure: error: Could not link against -lGLU !


I am running under Raspberrian

the config log said:
configure:6202: g++ -o conftest -g -O2 -pthread   -lGL  conftest.cpp -lglu32  >&5
/usr/bin/ld: cannot find -lglu32
collect2: error: ld returned 1 exit status
configure:6202: $? = 1
