### ISSUE TITLE
flickering with huge log. 

### ISSUE THREAD

**Issue by obiwankennedy** [acaudwell/Gource#40]
I ran gource on svn repository of more than 42 0000 commits. Some branches are flickering because the position of the center is moving between two positions. It gives headache to watch that. 

http://blog.rolisteam.org/file/gource_issue40.mp4

**Comment by acaudwell** [comment]
Thanks for the video.

This might be the elasticity setting (-e, --elasticity FLOAT). If you set it to 0 (the default) it may go away.

If its not that simple, maybe you can send me a log file to look at (--output-custom-log will generate one you can easily make redactions to if nessisary).

**Comment by obiwankennedy** [comment]
I did not set any elasticity settings my call was: 
gource --seconds-per-day 1 --time-scale 4.0

I will try to get log file.

**Comment by acaudwell** [comment]
Ok. I think the issue is --time-scale 4.0 reducing the accuracy of the physics which shows up with a giant repository.

I'd suggest using the default time-scale, then post-process the resulting video later if you want to speed it up without the physics artefacts.
