### ISSUE TITLE
Gource not working on Windows

### ISSUE THREAD

**Issue by Stoffe** [acaudwell/Gource#41]
Running Windows 10.
Latest Git for Windows is installed.
Git path in %PATH%
Running Latest GitExtensions.

Running Gource from GitExtensions results in nothing... :(

Running Gource from commandline, results in an error:
gource: unable to find git.exe
Try 'gource --help' for more information.

There is no information about git in the --help or -h option.

Please advice!

UPDATE:
Ok, found that I had to run the cmd file under cmd dir.
I with you would update some information both about the GIT path required AND, about running the cmd.

Still havent gotten it to work with GitExtensions though...

**Comment by michaelpalumbo** [comment]
hmm, I am also experiencing this very same issue. --note-- I have used gource successfully on macosx, and was quite happy with it, but am now on a windows machine. I see this issue was closed on feb 19, 2016, how was it resolved?

**Comment by acaudwell** [comment]
Thanks for the update.
