### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by rybak** [acaudwell/Gource#44]
### Keyboard controls manual is not full

Many of the keys are not covered, and it's not always obvious what they do.

For example, `[` `]` - I think they change "elasticity", but I'm not sure.

`r` - show/hide first (?) level directories edges. `y` - show/hide all edges

`q` `w` `t` - show/hide some debug output.

`d` - change level at which directory names are shown.

`f` - cycle through "show filenames" "show only extensions" "hide filenames"

### Scales

It's not clear what is a "time scale" in gource. "user scale" changes sizes of avatars, which should be mentioned in manual too.

**Comment by acaudwell** [comment]
I have now documented these controls (the non developer ones) in the manual, and also clarified that user scale applies to avatars. Thanks for the comprehensive list! Wasn't sure what else to say about time scale (it scales time).

**Comment by rybak** [comment]
What are the units of time scale?
