### ISSUE TITLE
Position of accents is wrong

### ISSUE THREAD

**Issue by tienne-B** [acaudwell/Gource#48]
The position of accents on letters is too low. As an example, on the capital E with acute accent (É, U+00C9), the accent is pushed under the top bar, rendering it impossible to distinguish.

**Comment by acaudwell** [comment]
I did a test and it looks to be much the same as it appears in your comment (above the top bar). The bundled font is an old version of FreeSans though some distributions may override and use the version installed on the system.

Maybe you could supply a screen shot top help diagnose the issue?
