### ISSUE TITLE
[Request] Show file directories with key press

### ISSUE THREAD

**Issue by RowenStipe** [acaudwell/Gource#50]
I was hoping it could be possible to add in the feature to show just directory names with just a keystroke.

Would make a screenshot like this: ![](http://i.imgur.com/U1snpap.png) look a little snazzyier than trying to time it all out.

If there's documentation on how to do this I certainly didn't see it.

**Comment by acaudwell** [comment]
In Gource:
D cycles display modes for directory names
F cycling display modes for file names

Not currently documented, I will do that now.

You can also accomplish this with --hide dirnames (there are various other hide options too)

**Comment by RowenStipe** [comment]
Aha~ Good to know =)
