### ISSUE TITLE
segmentation fault (homebrew)

### ISSUE THREAD

**Issue by lufeihaidao** [acaudwell/Gource#51]
``` bash
> gource
[1]    26918 segmentation fault  gource
```

I install it from homebrew on MAC.

```bash
> brew install gource
==> Installing dependencies for gource: boost, glew, sdl2, webp, sdl2_image
```

**Comment by smuda** [comment]
I installed from brew and I'm also getting segmentation fault.

```
> gource
Segmentation fault: 11
```

I'm on MacOSX 10.11.3.

**Comment by xnextx** [comment]
I have OS X El Capitan and also have this problem :( I installed gource the brew and sudo port but there is always the same error.

**Comment by ankon** [comment]
I can also reproduce this on 10.11.3 with the brew-installed version (0.43.2), here's the backtraces etc: https://gist.github.com/ankon/26a36f67a6985f5129c5

**Comment by acaudwell** [comment]
I think that log suggests it might be crashing in boost filesystem? Likely candidate as it is a C++ library and might be incompatible if it was built with a different compiler than what was used to build gource.

Try removing and reinstalling boost and then reinstall gource.

**Comment by xnextx** [comment]
Thank you for your help.
I did as you say, but it unfortunately did not work :( I still have the same error :
https://gist.github.com/xnextx/0a30bd2410c4e230b012

**Comment by xnextx** [comment]
Yeah, I was able to run on os x gource El Capitan!

Solution:
-I Removed the brew and port
-I install port
-Then You must install:
sudo port install pcre libsdl libsdl_image ftglsudo glew opencv
-FINISHED!

**Comment by acaudwell** [comment]
Good to hear you got it working. Not sure about that list of packages (ftgl, opencv).

**Comment by lufeihaidao** [comment]
@xnextx I found `ftgl` and `opencv` were not installed in homebrew when I installed gource. In homebrew there are `opencv` and `opencv3`. Also `sdl2` and `sdl2_image` were installed rather than `sdl` and `sdl_image`.

**Comment by Diokuz** [comment]
Not working for me :(
Also

```
Error: Port ftglsudo not found
```

**Comment by kessiler** [comment]
Not working for me.
Getting [1]    22772 segmentation fault  gource

**Comment by acaudwell** [comment]
Could be the same issue seen here: https://github.com/facebook/osquery/issues/1781

Also Homebrew. Crash is in the same place: boost::filesystem::detail::status.

**Comment by bfontaine** [comment]
Does `brew rm gource && brew install -s gource` work for you? I’m working on fixing the Homebrew package after hitting this issue. If you can determine that it’s Homebrew that’s causing the issue it’s a good idea to report it to us as well so we can fix it (or better: make a pull-request) :smiley:

**Comment by bosr** [comment]
I did not test with `ports`, but with Homebrew at least `gource` does work if installed from source, as @bfontaine suggested :+1:

**Comment by raindev** [comment]
Segfaults on OS X 10.11.3 when installed from Homebrew as a binary. Could attach crash report and dependency versions if needed. Works when installed from source.

**Comment by bfontaine** [comment]
I just rebuilt Homebrew’s bottle (= precompiled version); it should be fine now.

**Comment by bosr** [comment]
Works perfectly fine, thank you @bfontaine :)

**Comment by kessiler** [comment]
@bfontaine thanks, working well ! I think you should bump a version. Most people have cached it on brew..

**Comment by acaudwell** [comment]
Thanks for your efforts figuring this out.

**Comment by smuda** [comment]
@bfontaine `brew rm gource && brew install -s gource` works well. Thank you!

**Comment by bfontaine** [comment]
@kessiler Good point; I bumped the revision. :+1:
