### ISSUE TITLE
[Feature Request] [Maybe I'm doing it wrong] include a submodule as part of the visualisation

### ISSUE THREAD

**Issue by samdeman22** [acaudwell/Gource#65]
So, I'm working on something at the moment where I am moving my back-end stuff into a separate git repo, and re-including it in the original project as a submodule. However when you try to visualise the main project the folder containing the submodule repo appears empty.
I think it would be cool to see this change over to a submodule reflected in the visualisation, is it possible already?

**Comment by mathieu-aubin** [comment]
@samdeman22 

My suggestion won't help in the long run but... it **could/will** work as last resort (with patience i guess)...Have you tried generating custom logs for **boths** repos then condensing/merging into one log (modify at will!)?

from [Gource README](https://github.com/acaudwell/Gource/blob/master/README):
```
# gource --output-custom-log my-project-custom.log
```

that you then process with gource...
```
# gource merged-log-filename.log
```

I've tried merging two logs then changing dates/files randomly... gource reads logs and does what it does best! I hope this can help you somehow.

**Comment by acaudwell** [comment]
https://github.com/acaudwell/Gource/wiki/Visualizing-Multiple-Repositories

**Comment by mathieu-aubin** [comment]
Good to know i wasn't totally lost - hahha thx @acaudwell
