### ISSUE TITLE
failed to generate log file

### ISSUE THREAD

**Issue by leonschwanitz** [acaudwell/Gource#67]
Hello, i become an error: "gource: failed to generate log file".
![failed](https://cloud.githubusercontent.com/assets/3659674/15322991/05d1f634-1c40-11e6-848f-671ae28ce595.PNG)

**Comment by acaudwell** [comment]
Usually this is caused by you not having the command line tools available in PATH for the version control system you are using (e.g. git.exe).

**Comment by pankaj-kvhld** [comment]
i get the same error despite having git on my systems path. Windows 7

**Comment by ferenczy** [comment]
What about an incompatibility with Git. I'm currently using Git 2.8 (Cygwin) and 2.12 (Windows), on both it fails to generate the log file. I have Git in `PATH` on both Windows and Cygwin.
