### ISSUE TITLE
Since I don't know where else to put this, I'm having problems...

### ISSUE THREAD

**Issue by LemonadeWarrior** [acaudwell/Gource#68]
I am on Ubuntu 14.04 64 bit

I've installed Gource (hopefully correctly) and when I go to the terminal to type in commands it shows an error:

![gource error1](https://cloud.githubusercontent.com/assets/19496160/15439503/ae695aaa-1e96-11e6-87d2-ed1bac2e3339.png)

"gource: directory not supported
Try 'gource --help' for more information."

I know I'm doing something wrong, but I don't know what. So I’ve come to you master coders for help when searching myself has failed.

Furthermore, I'm not sure if I can do the thing I want to with Gource. Which is to create a visualization of Dwarf Fortresses' development... I hope you guys let me know if I’m misguided...

Thank you for your Replies :)

**Comment by mathieu-aubin** [comment]
Hi!
I believe you are not into a git repository directory (a folder that has a .git inside)

**Comment by mathieu-aubin** [comment]
As far as your Dwarf forteressesss thing - is there a public source code repository? If so... there's a big change you will be able to!

**Comment by LemonadeWarrior** [comment]
Thanks for replying.

At the risk of sounding stupid, I have to ask...

How do I get a .git?

I would have replied to you quicker If I hadn't been stubborn in trying to figure it out.

I have downloaded [Git](https://git-scm.com/)(I'm just guessing I need this), but I can't figure out how to get a '.git' using it...

Thank you for replying.

**Comment by mathieu-aubin** [comment]
okay, so you probably did something like (on the console)
```
sudo apt-get install git
```
That asked you if you wanted to install git, you said yes i'm sure!...
This website here, github.com, contains sourcecode repository managed by the git versioning system. Let's say you wanted to download the entire source project (and history, remember git is a version management system)...
going to : https://github.com/acaudwell/Gource
will bring you to Gource's git repository. Now, let's open your console and cd to a temporary directory (/tmp is what you want!) so in a terminal do this:
```
cd /tmp
```
you've moved to /tmp folder. Now, going back to Gource on github.com... On the main page, up top, you can see this:
<a href="http://i.imgur.com/4wNsdfw.png">
  <img src="http://imgur.com/4wNsdfwl.png" />
</a>
That button that says Clone or download, click on it. This will give you the option to download a zip archive or, it'll give you a link ending with a .git file -- that's what we want!! Copy it! You now have:
```
https://github.com/acaudwell/Gource.git
```
in your clipboard. Go back to your console, make sure you are still in /tmp by typing the command:
```
pwd
```
To get (or clone) Gource's git repository, use git clone and the url you got in your clipboard (you can paste in a terminal using CTRL+SHIFT+V)
```
git clone https://github.com/acaudwell/Gource.git
```
Hey, what? Yeah, it's downloading the entire Git repository for gource!!! Into the directory /tmp/Gource. cd into that (cd /tmp/Gource) and then type: gource

Enjoy

**Comment by mathieu-aubin** [comment]
Remember, google is your friend!

**Comment by LemonadeWarrior** [comment]
Thank you SO MUCH.

![screenshot from 2016-05-20 20 30 38](https://cloud.githubusercontent.com/assets/19496160/15445703/f7d2660e-1ec9-11e6-830d-d3ab0906c174.png)

I've been trying to get this to work all day and now It finally works!

I also swear I tried what you showed.... Well whatever It works :)

so Thank You again!

**Comment by Gamerappa** [comment]
make a windows way. this is a ubuntu way and i dont want to install Gource on my virtual machine

**Comment by mathieu-aubin** [comment]
get GIT
clone GOURCE repo
execute GOURCE
learn respect and politeness.
