### ISSUE TITLE
`Unrecognized option '-start-date'.

### ISSUE THREAD

**Issue by QuantumInformation** [acaudwell/Gource#70]
I tried the following

`gource --hide dirnames --seconds-per-day 1 --auto-skip-seconds 1 -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.mp4 --start-date '2015-07-07' `

but `i get the error

`Unrecognized option '-start-date'.
Error splitting the argument list: Option not found`

**Comment by acaudwell** [comment]
Looks like you're passing start-date to ffmpeg instead of gource.

**Comment by QuantumInformation** [comment]
Ah, ok thanks

**Comment by lee-b-sk** [comment]
Seeing a similar issue here, without any use of ffmpeg

```
$ gource --start-date="2002-02-16 00:00:00 +0"                                                                                 gource: unknown option start-date=2002-02-16 00:00:00 +0
Try 'gource --help' for more information.
```

**Comment by acaudwell** [comment]
You just need to replace the `=` with a space.
