### ISSUE TITLE
Gource with Source Tree

### ISSUE THREAD

**Issue by MinecraftPlaye** [acaudwell/Gource#82]
Hi,

I don't know if this is the right place to put it in, but because I don't know any other place I'm posting this here:

I'm using SourceTree 1.9.6.1 with the embedded git version 2.8.1 and the embedded mercurial version 3.7.3. (besides, I'm using Windows)
How can I make now a video of my repository?

My repository is located here: B:\Sonstiges\Programming\Test\
and my embedded git is located here: C:\Users\User\AppData\Local\Atlassian\SourceTree\git_local\

When I know try to run it in my repository it always tells me that the git.exe could not be found and when I run it from  C:\Users\User\AppData\Local\Atlassian\SourceTree\git_local\bin it always tells something about invalid directionary.

**Comment by Inzanit** [comment]
Source Tree is just your Git client. Run Gource from the root of your project folder through Git bash or CMD.
