### ISSUE TITLE
Wiki has no command line option listing page

### ISSUE THREAD

**Issue by MrStonedOne** [acaudwell/Gource#89]
I'd rather not have to open two terminal windows just so i can see the command line options on one monitor and type out the command on the other monitor. No excuse for not having that same listing in a wiki page.

**Comment by ministryofwrestling** [comment]
Refer to the project readme

https://github.com/acaudwell/Gource

**Comment by MrStonedOne** [comment]
Storing that kind of shit in the project readme is counter intuitive. Most projects on github use that space to introduce the application, explain what it does or how it's useful, and explain how to compile build the project.

Usage instructions is usually a link to a page on the wiki
