### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by merschformann** [acaudwell/Gource#92]
First of all thanks for the great work! I really love the project!
I'm just wondering whether there is already a way to select the display to show output on for fullscreen or some borderless maximized mode? I would really love to run two gource instances on my two monitors in parallel. I'm currently trying to wrap it up in some very simple screensaver. ;)
Or did someone already do this and I missed it? It's kind of obvious I guess. ^^

**Comment by acaudwell** [comment]
There is a now a --screen NUMBER option to launch on a different screen.
