### ISSUE TITLE
minimum user size

### ISSUE THREAD

**Issue by nschloe** [acaudwell/Gource#93]
I would like to visualize a project which starts out small and eventually becomes quite big. So big that the user avatars are only a few pixels in size. There is ` --user-scale` to work with indeed, but setting this to a value that gives the avatars a good scaling towards the end (about `10` in my case) makes them ridiculously large when the animation starts.

A good way out would perhaps be a ` --min-avatar-size` parameter.

**Comment by aaronfranke** [comment]
Bump, this would be awesome. Right now avatars are just a few pixels and are super tiny.

**Comment by 0jrp0** [comment]
@acaudwell , I would like to take this up and put together a pull request. I will need some guidance on where the global scaling operation is happening. I see that users are added into vbo here: https://github.com/acaudwell/Gource/blob/9354ebfec4766ffe314e95eb08c3f9d396cd4b44/src/gource.cpp#L2240

But I suspect there is a global scaling operation somewhere that applies to all vbo types. We could put a min clamp here in this area or we could put the exception where the global scaling is.

What are your thoughts on the best approach?

**Comment by 0jrp0** [comment]
I've never coded OpenGL before, but I'm guessing the combo of the Frustum:
https://github.com/acaudwell/Gource/blob/9354ebfec4766ffe314e95eb08c3f9d396cd4b44/src/gource.cpp#L2377

And the scale of the user icon are related to how tiny they get. Because as the camera zooms out, files, dirs, user icons, etc. etc. get tiny. But the usernames still stay a fixed size. In an ideal setup, the scale of the user icon and the font size of the username stay relative to one another with some minimum clamping as the camera zooms out to see the entire tree.

I'm working on a project with 200k files, so it becomes pretty acute towards the end.

**Comment by acaudwell** [comment]
You could try using something like `screen_user_height = dims.y/-camera.getPos().z` (z is negative) to determine if dims is too small, and then scale up dims. The camera moves on the z axis to zoom in and out, I'm pretty sure the field of view is always constant so you can ignore it.

**Comment by 0jrp0** [comment]
I made some progress with the following patch:

```
diff --git a/src/gource.cpp b/src/gource.cpp
index 7c9bd40..4d54162 100644
--- a/src/gource.cpp
+++ b/src/gource.cpp
@@ -2237,7 +2237,17 @@ void Gource::updateVBOs(float dt) {
             float alpha = user->getAlpha();
             vec3 col   = user->getColour();

-            user_vbo.add(user->graphic->textureid, user->getPos() - user->dims*0.5f, user->dims, vec4(col.x, col.y, col.z, alpha));
+            vec2 scaled_dims = user->dims;
+
+            scaled_dims.x *= 0.07 / (user->dims.x / -camera.getPos().z);
+            scaled_dims.y *= 0.07 / (user->dims.y / -camera.getPos().z);
+            // screen_user_height = dims.y/-camera.getPos().z
+            //user->dims *= 2.0f; // -camera.getPos().z; // std::max(18.0f, user->dims.y);
+            fprintf(stderr, "user: %f %f\n", user->dims.x/-camera.getPos().z, user->dims.y/-camera.getPos().z);
+            fprintf(stderr, "scaled: %f %f\n", scaled_dims.x, scaled_dims.y);
+
+            // user_vbo.add(user->graphic->textureid, user->getPos() - user->dims*0.5f, user->dims, vec4(col.x, col.y, col.z, alpha));
+            user_vbo.add(user->graphic->textureid, user->getPos() - scaled_dims*0.5f, scaled_dims, vec4(col.x, col.y, col.z, alpha));

             //draw actions
             user->updateActionsVBO(action_vbo);
```

There's a few issues with it. The fact that I used the constant 0.07 is very specific to the image that I'm using which is 20x20. The second issue is that when zoomed in, there is a lot of empty margin / padding around the image with the username set much higher. As you zoom out, the username and the image compress together. But the image does remain constant no matter what the zoom level .. just like the font of the username.

I'll poke at it some more tomorrow.

**Comment by 0jrp0** [comment]
The pull request resolves putting the behavior behind a flag and the constant issue after going through the math a bit. It doesn't resolve the excess padding around the icon when you zoom in. I'm not sure where that comes from?
